apiVersion: v1
kind: Service
metadata:
  name: nginx-ldap-auth
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ldap-auth
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: docker.io/tpimenta/nginx-ldap-auth:v1.0.6
        name: nginx-ldap-auth
        command:
        - "/usr/local/bin/nginx-ldap-auth"
        - "--config"
        - "/etc/nginx-ldap-auth/config.yaml"
        ports:
        - name: http
          containerPort: 5555
        volumeMounts:
        - name: config
          mountPath: /etc/nginx-ldap-auth
      volumes:
      - name: config
        secret:
          secretName: nginx-ldap-auth
          items:
          - key: config.yaml
            path: config.yaml
