---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - deploy.yml
  - rbac.yml

configMapGenerator:
  - name: forecastle-config
    files:
      - config.yaml
