apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - internal
  - external
  - ../bases/configs

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1beta1
      kind: Role
      name: nginx-ingress-role
    path: patch/rbac.yml
  - target:
      group: ""
      version: v1
      kind: Service
      name: ingress-nginx-metrics
    path: patch/sm-service.yml
