kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  labels:
    app: ingress-nginx
data:
  proxy-body-size: 30m
  proxy-connect-timeout: '10'
  proxy-read-timeout: '120'
  proxy-send-timeout: '120'
  http-redirect-code: '301'
  use-proxy-protocol: 'true'
