apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases/controller

nameSuffix: "-internal"

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: nginx-ingress-controller
    path: patch/daemonset.yml
  - target:
      group: ""
      version: v1
      kind: Service
      name: ingress-nginx
    path: patch/service.yml
