apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ingress-nginx
  name: ingress-nginx
spec:
  endpoints:
  - interval: 10s
    port: metrics
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
      matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app: ingress-nginx