apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-internal
  labels:
    app: ingress-internal
data:
  proxy-body-size: 10m
  http-redirect-code: "301"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-external
  labels:
    app: ingress-external
data:
  proxy-body-size: 10m
  http-redirect-code: "301"